<?php
defined('BASEPATH') or exit('No direct script access allowed');

class M_validations extends CI_Model
{

    public $rules = [
        'application_form' => [

            ['field' => 's_first_position', 'label' => 'First Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_first_name', 'label' => 'First Name', 'rules' => 'trim|required'],
            ['field' => 's_last_name', 'label' => 'Last Name', 'rules' => 'trim|required'],
            ['field' => 's_birth_date', 'label' => 'Birth Date', 'rules' => 'trim|required|callback_checkBirth'],
            ['field' => 's_birth_place', 'label' => 'Birth Place', 'rules' => 'trim|required'],
            ['field' => 's_date_available', 'label' => 'Date Available', 'rules' => 'trim|required|callback_checkDate'],
            ['field' => 's_civil_status', 'label' => 'Civil Status', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_email_address',  'label' => 'Email Address', 'rules' => 'trim|valid_email|is_unique[ac_personal_info.email_address]', 'errors' => ['is_unique' => 'This %s is already registered with us!']],
            ['field' => 's_mobile_number', 'label' => 'Mobile Number', 'rules' => 'trim|numeric|exact_length[11]|regex_match[/^(0)\d{0}/]|is_unique[ac_personal_info.mobile_number]', 'errors' => ['is_unique' => 'This %s is already registered with us!']],
            ['field' => 's_nationality', 'label' => 'Nationality', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_height', 'label' => 'Height (in cm)', 'rules' => 'trim|required'],
            ['field' => 's_weight', 'label' => 'Weight (in kg)', 'rules' => 'trim|required'],
            ['field' => 's_bmi', 'label' => 'BMI', 'rules' => 'trim|required'],
            ['field' => 's_home_address', 'label' => 'House/Unit/Flr #, Bldg Name, Blk or Lot #', 'rules' => 'trim|required'],
            ['field' => 's_province', 'label' => 'Province', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_city', 'label' => 'City', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_country', 'label' => 'Country', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_kin_address', 'label' => 'Address', 'rules' => 'trim|required'],
            ['field' => 's_course', 'label' => 'Course', 'rules' => 'trim|required'],
            ['field' => 's_school_name', 'label' => 'School', 'rules' => 'trim|required'],
            ['field' => 's_inclusive_years_from', 'label' => 'Inclusive Date From', 'rules' => 'trim|required'],
            ['field' => 's_inclusive_years_to', 'label' => 'Inclusive Date To', 'rules' => 'trim|required'],
        ],

        'edit_shipboard_application_form' => [

            ['field' => 'e_first_position', 'label' => 'First Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_tentative_vessel', 'label' => 'Tentative Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_type_of_crew', 'label' => 'Type of Crew', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_first_name', 'label' => 'First Name', 'rules' => 'trim|required'],
            ['field' => 'e_last_name', 'label' => 'Last Name', 'rules' => 'trim|required'],
            ['field' => 'e_birth_date', 'label' => 'Birth Date', 'rules' => 'trim|required|callback_checkBirth'],
            ['field' => 'e_birth_place', 'label' => 'Birth Place', 'rules' => 'trim|required'],
            ['field' => 'e_date_available', 'label' => 'Date Available', 'rules' => 'trim|required|callback_checkDate'],
            ['field' => 'e_civil_status', 'label' => 'Civil Status', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_email_address',  'label' => 'Email Address', 'rules' => 'trim|valid_email'],
            ['field' => 'e_mobile_number', 'label' => 'Mobile Number', 'rules' => 'trim|numeric|exact_length[11]|regex_match[/^(0)\d{0}/]'],
            // ['field' => 'e_religion', 'label' => 'Religion', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_nationality', 'label' => 'Nationality', 'rules' => 'trim|required|callback_validate_select'],
            // ['field' => 'e_sss_no', 'label' => 'SSS No', 'rules' => 'trim|required'],
            // ['field' => 'e_tin_no', 'label' => 'TIN No', 'rules' => 'trim|required'],
            // ['field' => 'e_philhealth_no', 'label' => 'Philhealth No', 'rules' => 'trim|required'],
            // ['field' => 'e_pag_ibig_no', 'label' => 'Pag-Ibig No', 'rules' => 'trim|required'],
            ['field' => 'e_height', 'label' => 'Height (in cm)', 'rules' => 'trim|required'],
            ['field' => 'e_weight', 'label' => 'Weight (in kg)', 'rules' => 'trim|required'],
            ['field' => 'e_bmi', 'label' => 'BMI', 'rules' => 'trim|required'],
            ['field' => 'e_home_address', 'label' => 'House/Unit/Flr #, Bldg Name, Blk or Lot #', 'rules' => 'trim|required'],
            ['field' => 'e_province', 'label' => 'Province', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_city', 'label' => 'City', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_country', 'label' => 'Country', 'rules' => 'trim|required|callback_validate_select'],
            // ['field' => 'e_father_name', 'label' => "Father's Name", 'rules' => 'trim|required'],
            // ['field' => 'e_mother_name', 'label' => "Mother's Name", 'rules' => 'trim|required'],
            ['field' => 'e_kin_address', 'label' => 'Address', 'rules' => 'trim|required'],
            ['field' => 'e_course', 'label' => 'Course', 'rules' => 'trim|required'],
            ['field' => 'e_school_name', 'label' => 'School', 'rules' => 'trim|required'],
            ['field' => 'e_inclusive_years_from', 'label' => 'Inclusive Date From', 'rules' => 'trim|required'],
            ['field' => 'e_inclusive_years_to', 'label' => 'Inclusive Date To', 'rules' => 'trim|required'],
            // ['field' => 'e_school_address', 'label' => 'School Address', 'rules' => 'trim|required'],
        ],

        'e_crew_info_form' => [

            ['field' => 'e_first_name', 'label' => 'First Name', 'rules' => 'trim|required'],
            ['field' => 'e_last_name', 'label' => 'Last Name', 'rules' => 'trim|required'],
            ['field' => 'e_birth_date', 'label' => 'Birth Date', 'rules' => 'trim|required|callback_checkBirth'],
            ['field' => 'e_birth_place', 'label' => 'Birth Place', 'rules' => 'trim|required'],
            ['field' => 'e_civil_status', 'label' => 'Civil Status', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_email_address',  'label' => 'Email Address', 'rules' => 'trim|valid_email'],
            ['field' => 'e_mobile_number', 'label' => 'Mobile Number', 'rules' => 'trim|numeric|exact_length[11]|regex_match[/^(0)\d{0}/]'],
            // ['field' => 'e_religion', 'label' => 'Religion', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_nationality', 'label' => 'Nationality', 'rules' => 'trim|required|callback_validate_select'],
            // ['field' => 'e_sss_no', 'label' => 'SSS No', 'rules' => 'trim|required'],
            // ['field' => 'e_tin_no', 'label' => 'TIN No', 'rules' => 'trim|required'],
            // ['field' => 'e_philhealth_no', 'label' => 'Philhealth No', 'rules' => 'trim|required'],
            // ['field' => 'e_pag_ibig_no', 'label' => 'Pag-Ibig No', 'rules' => 'trim|required'],
            ['field' => 'e_height', 'label' => 'Height (in cm)', 'rules' => 'trim|required'],
            ['field' => 'e_weight', 'label' => 'Weight (in kg)', 'rules' => 'trim|required'],
            ['field' => 'e_bmi', 'label' => 'BMI', 'rules' => 'trim|required'],
            ['field' => 'e_home_address', 'label' => 'House/Unit/Flr #, Bldg Name, Blk or Lot #', 'rules' => 'trim|required'],
            ['field' => 'e_province', 'label' => 'Province', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_city', 'label' => 'City', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_country', 'label' => 'Country', 'rules' => 'trim|required|callback_validate_select'],

            // ['field' => 'e_father_name', 'label' => "Father's Name", 'rules' => 'trim|required'],
            // ['field' => 'e_mother_name', 'label' => "Mother's Name", 'rules' => 'trim|required'],
            ['field' => 'e_kin_address', 'label' => 'Address', 'rules' => 'trim|required'],

            ['field' => 'e_course', 'label' => 'Course', 'rules' => 'trim|required'],
            ['field' => 'e_school_name', 'label' => 'School', 'rules' => 'trim|required'],
            ['field' => 'e_inclusive_years_from', 'label' => 'Inclusive Date From', 'rules' => 'trim|required'],
            ['field' => 'e_inclusive_years_to', 'label' => 'Inclusive Date To', 'rules' => 'trim|required'],
            // ['field' => 'e_school_address', 'label' => 'School Address', 'rules' => 'trim|required'],
        ],
        'add_module_form' => [
            ['field' => 'module_name', 'label' => 'Module Name', 'rules' => 'trim|required'],
            ['field' => 'url', 'label' => 'URL', 'rules' => 'trim|required'],
            ['field' => 'icon', 'label' => 'Icon', 'rules' => 'trim|required'],
        ],
        'edit_module_form' => [
            ['field' => 'e_module_name', 'label' => 'Module Name', 'rules' => 'trim|required'],
            ['field' => 'e_module_url', 'label' => 'URL', 'rules' => 'trim|required'],
            ['field' => 'e_module_icon', 'label' => 'Icon', 'rules' => 'trim|required'],
        ],
        'add_sub_module_form' => [
            ['field' => 'module', 'label' => 'Module', 'rules' => 'trim|required'],
            ['field' => 'sub_module', 'label' => 'Sub Module', 'rules' => 'trim|required'],
            ['field' => 'target_link', 'label' => 'Target Link', 'rules' => 'trim|required'],
            ['field' => 'sub_module_url', 'label' => 'URL', 'rules' => 'trim|required'],
        ],
        'edit_sub_module_form' => [
            ['field' => 'e_module', 'label' => 'Module', 'rules' => 'trim|required'],
            ['field' => 'e_sub_module', 'label' => 'Sub Module', 'rules' => 'trim|required'],
            ['field' => 'e_target_link', 'label' => 'Target Link', 'rules' => 'trim|required'],
            ['field' => 'e_sub_module_url', 'label' => 'URL', 'rules' => 'trim|required'],
        ],
        'add_node_form' => [
            ['field' => 'sub_module', 'label' => 'Sub Module', 'rules' => 'trim|required'],
            ['field' => 'node', 'label' => 'Node', 'rules' => 'trim|required'],
            ['field' => 'node_url', 'label' => 'URL', 'rules' => 'trim|required'],
        ],
        'edit_node_form' => [
            ['field' => 'e_sub_module', 'label' => 'Sub Module', 'rules' => 'trim|required'],
            ['field' => 'e_node_name', 'label' => 'Node', 'rules' => 'trim|required'],
            ['field' => 'e_node_url', 'label' => 'URL', 'rules' => 'trim|required'],
        ],
        'nat_result_form' => [
            ['field' => 'n_aptitude_test_score', 'label' => 'NAT Result', 'rules' => 'trim|required'],
        ],
        'certificate_form' => [
            ['field' => 'cert_code', 'label' => 'Certificate Code', 'rules' => 'trim|required'],
            ['field' => 'cert_name', 'label' => 'Certificate Name', 'rules' => 'trim|required']
        ],
        'e_certificate_form' => [
            ['field' => 'e_cert_code', 'label' => 'Certificate Code', 'rules' => 'trim|required'],
            ['field' => 'e_cert_name', 'label' => 'Certificate Name', 'rules' => 'trim|required']
        ],
        'license_form' => [
            ['field' => 'license_code', 'label' => 'License Code', 'rules' => 'trim|required'],
            ['field' => 'license_name', 'label' => 'License Name', 'rules' => 'trim|required']
        ],
        'e_license_form' => [
            ['field' => 'e_license_code', 'label' => 'License Code', 'rules' => 'trim|required'],
            ['field' => 'e_license_name', 'label' => 'License Name', 'rules' => 'trim|required']
        ],
        'position_form' => [
            ['field' => 'position_code', 'label' => 'Position Code', 'rules' => 'trim|required'],
            ['field' => 'position_name', 'label' => 'Position Name', 'rules' => 'trim|required'],
            ['field' => 'department', 'label' => 'Department', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'maximum_age_new', 'label' => 'Maximum Age (New Crew)', 'rules' => 'trim|required'],
            ['field' => 'maximum_age_ex', 'label' => 'Maximum Age (Ex Crew)', 'rules' => 'trim|required'],
            ['field' => 'minimum_exp', 'label' => 'Minimum Experience', 'rules' => 'trim|required'],
            ['field' => 'maximum_exp', 'label' => 'Maximum Experience', 'rules' => 'trim|required']
        ],
        'e_position_form' => [
            ['field' => 'e_position_code', 'label' => 'Position Code', 'rules' => 'trim|required'],
            ['field' => 'e_position_name', 'label' => 'Position Name', 'rules' => 'trim|required'],
            ['field' => 'e_department', 'label' => 'Department', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_maximum_age_new', 'label' => 'Maximum Age (New Crew)', 'rules' => 'trim|required'],
            ['field' => 'e_maximum_age_ex', 'label' => 'Maximum Age (Ex Crew)', 'rules' => 'trim|required'],
            ['field' => 'e_minimum_exp', 'label' => 'Minimum Experience', 'rules' => 'trim|required'],
            ['field' => 'e_maximum_exp', 'label' => 'Maximum Experience', 'rules' => 'trim|required']
        ],
        'interview_form' => [
            ['field' => 'points_of_interview', 'label' => 'Points of Interview', 'rules' => 'trim|required']
        ],
        'e_interview_form' => [
            ['field' => 'e_points_of_interview', 'label' => 'Points of Interview', 'rules' => 'trim|required']
        ],
        'add_vessel_form' => [
            ['field' => 'vsl_code', 'label' => 'Vessel Code', 'rules' => 'trim|required'],
            ['field' => 'vsl_name', 'label' => 'Vessel Name', 'rules' => 'trim|required'],
            ['field' => 'type_of_vessel', 'label' => 'Type of Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'type_of_engine', 'label' => 'Type of Engine', 'rules' => 'trim|required|callback_validate_select'],
        ],
        'edit_vessel_form' => [
            ['field' => 'e_vsl_code', 'label' => 'Vessel Code', 'rules' => 'trim|required'],
            ['field' => 'e_vsl_name', 'label' => 'Vessel Name', 'rules' => 'trim|required'],
            ['field' => 'e_type_of_vessel', 'label' => 'Type of Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_type_of_engine', 'label' => 'Type of Engine', 'rules' => 'trim|required|callback_validate_select'],
        ],
        'vessel_type_form' => [
            ['field' => 'vessel_code', 'label' => 'Vessel Code', 'rules' => 'trim|required'],
            ['field' => 'vessel_name', 'label' => 'Vessel Name', 'rules' => 'trim|required']
        ],
        'e_vessel_type_form' => [
            ['field' => 'e_vessel_code', 'label' => 'Vessel Code', 'rules' => 'trim|required'],
            ['field' => 'e_vessel_name', 'label' => 'Vessel Name', 'rules' => 'trim|required']
        ],
        'vessel_engine_form' => [
            ['field' => 'engine_code', 'label' => 'Engine Code', 'rules' => 'trim|required'],
            ['field' => 'engine_name', 'label' => 'Engine Name', 'rules' => 'trim|required']
        ],
        'e_vessel_engine_form' => [
            ['field' => 'e_engine_code', 'label' => 'Engine Code', 'rules' => 'trim|required'],
            ['field' => 'e_engine_name', 'label' => 'Engine Name', 'rules' => 'trim|required']
        ],
        'add_user_type_form' => [
            ['field' => 'full_name', 'label' => 'Full Name', 'rules' => 'trim|required'],
            ['field' => 'username', 'label' => 'User Name', 'rules' => 'trim|required'],
            ['field' => 'email_address',  'label' => 'Email Address', 'rules' => 'trim|required|valid_email|is_unique[user_account.email_address]', 'errors' => ['is_unique' => 'This %s is already registered with us!']],
            ['field' => 'phone_number', 'label' => 'Phone Number', 'rules' => 'trim|required|numeric|exact_length[11]|regex_match[/^(0)\d{0}/]|is_unique[ac_personal_info.mobile_number]', 'errors' => ['is_unique' => 'This %s is already registered with us!']],
            ['field' => 'password', 'label' => 'Password', 'rules' => 'trim|required'],
            ['field' => 'confirm_password', 'label' => 'Confirm Password', 'rules' => 'trim|required|matches[password]'],
            ['field' => 'user_type', 'label' => 'User Type', 'rules' => 'trim|required|callback_validate_select']
        ],
        'update_user_password_form' => [
            ['field' => 'p_password', 'label' => 'Password', 'rules' => 'trim|required'],
            ['field' => 'p_confirm_password', 'label' => 'Confirm Password', 'rules' => 'trim|required|matches[p_password]']
        ],
        'position_requirements_form' => [
            ['field' => 'position_list', 'label' => 'Position', 'rules' => 'trim|required|callback_validate_select']
        ],
        'position_licenses_form' => [
            ['field' => 'position_list', 'label' => 'Position', 'rules' => 'trim|required|callback_validate_select']
        ],
        'position_points_form' => [
            ['field' => 'position_list', 'label' => 'Position', 'rules' => 'trim|required|callback_validate_select']
        ],
        'existing_application_form' => [

            ['field' => 's_current_position', 'label' => 'Current Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_current_crew_status', 'label' => 'Crew Current Status', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_current_vessel', 'label' => 'Current Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_type_crew', 'label' => 'Type of Crew', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_first_name', 'label' => 'First Name', 'rules' => 'trim|required'],
            ['field' => 's_last_name', 'label' => 'Last Name', 'rules' => 'trim|required'],
            ['field' => 's_birth_date', 'label' => 'Birth Date', 'rules' => 'trim|required|callback_checkBirth'],
            ['field' => 's_birth_place', 'label' => 'Birth Place', 'rules' => 'trim|required'],
            ['field' => 's_civil_status', 'label' => 'Civil Status', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_email_address',  'label' => 'Email Address', 'rules' => 'trim|valid_email|is_unique[ac_personal_info.email_address]', 'errors' => ['is_unique' => 'This %s is already registered with us!']],
            ['field' => 's_mobile_number', 'label' => 'Mobile Number', 'rules' => 'trim|numeric|exact_length[11]|regex_match[/^(0)\d{0}/]|is_unique[ac_personal_info.mobile_number]', 'errors' => ['is_unique' => 'This %s is already registered with us!']],
            ['field' => 's_nationality', 'label' => 'Nationality', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_height', 'label' => 'Height (in cm)', 'rules' => 'trim|required'],
            ['field' => 's_weight', 'label' => 'Weight (in kg)', 'rules' => 'trim|required'],
            ['field' => 's_bmi', 'label' => 'BMI', 'rules' => 'trim|required'],
            ['field' => 's_home_address', 'label' => 'House/Unit/Flr #, Bldg Name, Blk or Lot #', 'rules' => 'trim|required'],
            ['field' => 's_province', 'label' => 'Province', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_city', 'label' => 'City', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_country', 'label' => 'Country', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 's_kin_address', 'label' => 'Address', 'rules' => 'trim|required'],
            ['field' => 's_course', 'label' => 'Course', 'rules' => 'trim|required'],
            ['field' => 's_school_name', 'label' => 'School', 'rules' => 'trim|required'],
            ['field' => 's_inclusive_years_from', 'label' => 'Inclusive Date From', 'rules' => 'trim|required'],
            ['field' => 's_inclusive_years_to', 'label' => 'Inclusive Date To', 'rules' => 'trim|required'],
        ],
        'add_watchlisted_form' => [
            ['field' => 'w_crew_name', 'label' => 'Crew Name', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'w_rank', 'label' => 'Rank / Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'w_department', 'label' => 'Department', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'w_vessel', 'label' => 'Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'w_certificates', 'label' => 'Certificates', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'w_registration_no', 'label' => 'E-Registration Number', 'rules' => 'trim|required'],
        ],
        'add_warning_letter_form' => [
            ['field' => 'w_crew_name', 'label' => 'Crew Name', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'w_rank', 'label' => 'Rank / Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'w_department', 'label' => 'Department', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'w_vessel', 'label' => 'Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'w_remarks', 'label' => 'Remarks', 'rules' => 'trim|required|callback_validate_select'],
        ],
        'add_dis_warning_leter' => [
            ['field' => 'awlm_rank', 'label' => 'Rank / Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'awlm_vessel', 'label' => 'Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'awlm_remarks', 'label' => 'Remarks', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'awlm_type_of_nre', 'label' => 'Reason', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'awlm_department', 'label' => 'Department', 'rules' => 'trim|required|callback_validate_select'],
        ],
        'add_flight_information_form' => [
            ['field' => 'flight_vessel', 'label' => 'Vessel', 'rules' => 'trim|required'],
            ['field' => 'f_flight_number', 'label' => 'Flight Number', 'rules' => 'trim|required'],
            ['field' => 'f_departure_country', 'label' => 'Departure Country', 'rules' => 'trim|required'],
            ['field' => 'f_departure_date', 'label' => 'Departure Date', 'rules' => 'trim|required'],
            ['field' => 'f_departure_time', 'label' => 'Departure Time', 'rules' => 'trim|required'],
            ['field' => 'f_destination_country', 'label' => 'Destination Country', 'rules' => 'trim|required'],
            ['field' => 'f_destination_date', 'label' => 'Destination Date', 'rules' => 'trim|required'],
            ['field' => 'f_destination_time', 'label' => 'Destination Time', 'rules' => 'trim|required'],
            ['field' => 'f_airfare', 'label' => 'Airfare', 'rules' => 'trim|required'],
            ['field' => 'f_airline', 'label' => 'Airline', 'rules' => 'trim|required'],
        ],
        'medical_form' => [
            ['field' => 'm_date_med_exam', 'label' => 'Date of Med. Exam', 'rules' => 'trim|required'],
            ['field' => 'm_medical_expiry_date', 'label' => 'Date of Expiry', 'rules' => 'trim|required'],
            ['field' => 'm_status', 'label' => 'Medical Status', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'm_height', 'label' => 'Height', 'rules' => 'trim|required'],
            ['field' => 'm_weight', 'label' => 'Weight', 'rules' => 'trim|required'],
        ],
        'edit_medical_form' => [
            ['field' => 'e_m_date_med_exam', 'label' => 'Date of Med. Exam', 'rules' => 'trim|required'],
            ['field' => 'e_m_medical_expiry_date', 'label' => 'Date of Expiry', 'rules' => 'trim|required'],
            ['field' => 'e_m_status', 'label' => 'Medical Status', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_m_height', 'label' => 'Height', 'rules' => 'trim|required'],
            ['field' => 'e_m_weight', 'label' => 'Weight', 'rules' => 'trim|required'],
        ],
        'edit_cmp_form' => [
            ['field' => 'c_sign_on', 'label' => 'Sign On', 'rules' => 'trim|required'],
            ['field' => 'c_end_contract', 'label' => 'End Contract', 'rules' => 'trim|required'],
            ['field' => 'c_onboard', 'label' => 'Months Onboard', 'rules' => 'trim|required'],
        ],
        'add_reporting_form' => [
            ['field' => 'r_date_availability', 'label' => 'Date Availability', 'rules' => 'trim|required|callback_checkDate'],
            ['field' => 'r_position', 'label' => 'Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'r_tentative_vessel', 'label' => 'Tentative Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'r_crew_evaluation', 'label' => 'Crew Evaluation', 'rules' => 'trim|required'],
        ],
        'un_toc_form' => [
            ['field' => 'toc_status', 'label' => 'Crew Status', 'rules' => 'trim|required|callback_validate_select'],
        ],
        'poea_contract_form' => [
            ['field' => 'c_sirb_no', 'label' => 'SIRB Number', 'rules' => 'trim|required'],
            ['field' => 'c_src_no', 'label' => 'SRC Number', 'rules' => 'trim|required'],
            ['field' => 'c_name_of_agent', 'label' => 'Name of Agent', 'rules' => 'trim|required'],
            ['field' => 'c_name_of_principal', 'label' => 'Name of Principal', 'rules' => 'trim|required'],
            ['field' => 'c_address_of_principal', 'label' => 'Address of Principal', 'rules' => 'trim|required'],
            ['field' => 'c_duration_contract', 'label' => 'Duration of Contract', 'rules' => 'trim|required'],
            ['field' => 'c_position', 'label' => 'Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'c_monthly_salary', 'label' => 'Basic Monthly Salary', 'rules' => 'trim|required'],
            ['field' => 'c_year_built', 'label' => 'Year Built', 'rules' => 'trim|required'],
            ['field' => 'c_flag', 'label' => 'Flag', 'rules' => 'trim|required'],
            ['field' => 'c_vessel_type', 'label' => 'Type of Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'c_classification_society', 'label' => 'Classification Society', 'rules' => 'trim|required'],
            ['field' => 'c_hours_of_work', 'label' => 'Hours of Work', 'rules' => 'trim|required'],
            ['field' => 'c_vessel_name', 'label' => 'Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'c_imo_number', 'label' => 'IMO Number', 'rules' => 'trim|required'],
            ['field' => 'c_gross_tonnage', 'label' => 'Gross Tonnage (GRT)', 'rules' => 'trim|required'],
            ['field' => 'c_overtime', 'label' => 'Overtime', 'rules' => 'trim|required'],
            ['field' => 'c_vacation_leave_with_pay', 'label' => 'Vacation Leave with Pay', 'rules' => 'trim|required'],
            ['field' => 'c_others', 'label' => 'Others', 'rules' => 'trim|required'],
            ['field' => 'c_total_salary', 'label' => 'Total Salary', 'rules' => 'trim|required'],
            ['field' => 'c_point_of_hire', 'label' => 'Point of Hire', 'rules' => 'trim|required'],
            ['field' => 'c_collective_agreement', 'label' => 'Collective Agreement', 'rules' => 'trim|required']
        ],
        'edit_poea_contract_form' => [
            ['field' => 'e_sirb_no', 'label' => 'SIRB Number', 'rules' => 'trim|required'],
            ['field' => 'e_src_no', 'label' => 'SRC Number', 'rules' => 'trim|required'],
            ['field' => 'e_name_of_agent', 'label' => 'Name of Agent', 'rules' => 'trim|required'],
            ['field' => 'e_name_of_principal', 'label' => 'Name of Principal', 'rules' => 'trim|required'],
            ['field' => 'e_address_of_principal', 'label' => 'Address of Principal', 'rules' => 'trim|required'],
            ['field' => 'e_duration_contract', 'label' => 'Duration of Contract', 'rules' => 'trim|required'],
            ['field' => 'e_position', 'label' => 'Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_monthly_salary', 'label' => 'Basic Monthly Salary', 'rules' => 'trim|required'],
            ['field' => 'e_year_built', 'label' => 'Year Built', 'rules' => 'trim|required'],
            ['field' => 'e_flag', 'label' => 'Flag', 'rules' => 'trim|required'],
            ['field' => 'e_vessel_type', 'label' => 'Type of Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_classification_society', 'label' => 'Classification Society', 'rules' => 'trim|required'],
            ['field' => 'e_hours_of_work', 'label' => 'Hours of Work', 'rules' => 'trim|required'],
            ['field' => 'e_vessel_name', 'label' => 'Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'e_imo_number', 'label' => 'IMO Number', 'rules' => 'trim|required'],
            ['field' => 'e_gross_tonnage', 'label' => 'Gross Tonnage (GRT)', 'rules' => 'trim|required'],
            ['field' => 'e_overtime', 'label' => 'Overtime', 'rules' => 'trim|required'],
            ['field' => 'e_vacation_leave_with_pay', 'label' => 'Vacation Leave with Pay', 'rules' => 'trim|required'],
            ['field' => 'e_others', 'label' => 'Others', 'rules' => 'trim|required'],
            ['field' => 'e_total_salary', 'label' => 'Total Salary', 'rules' => 'trim|required'],
            ['field' => 'e_point_of_hire', 'label' => 'Point of Hire', 'rules' => 'trim|required'],
            ['field' => 'e_collective_agreement', 'label' => 'Collective Agreement', 'rules' => 'trim|required']
        ],
        'promotion_poea_contract_form' => [
            ['field' => 'promotion_sirb_no', 'label' => 'SIRB Number', 'rules' => 'trim|required'],
            ['field' => 'promotion_src_no', 'label' => 'SRC Number', 'rules' => 'trim|required'],
            ['field' => 'promotion_name_of_agent', 'label' => 'Name of Agent', 'rules' => 'trim|required'],
            ['field' => 'promotion_name_of_principal', 'label' => 'Name of Principal', 'rules' => 'trim|required'],
            ['field' => 'promotion_address_of_principal', 'label' => 'Address of Principal', 'rules' => 'trim|required'],
            ['field' => 'promotion_duration_contract', 'label' => 'Duration of Contract', 'rules' => 'trim|required'],
            ['field' => 'promotion_position', 'label' => 'Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'promotion_monthly_salary', 'label' => 'Basic Monthly Salary', 'rules' => 'trim|required'],
            ['field' => 'promotion_year_built', 'label' => 'Year Built', 'rules' => 'trim|required'],
            ['field' => 'promotion_flag', 'label' => 'Flag', 'rules' => 'trim|required'],
            ['field' => 'promotion_vessel_type', 'label' => 'Type of Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'promotion_classification_society', 'label' => 'Classification Society', 'rules' => 'trim|required'],
            ['field' => 'promotion_hours_of_work', 'label' => 'Hours of Work', 'rules' => 'trim|required'],
            ['field' => 'promotion_vessel_name', 'label' => 'Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'promotion_imo_number', 'label' => 'IMO Number', 'rules' => 'trim|required'],
            ['field' => 'promotion_gross_tonnage', 'label' => 'Gross Tonnage (GRT)', 'rules' => 'trim|required'],
            ['field' => 'promotion_overtime', 'label' => 'Overtime', 'rules' => 'trim|required'],
            ['field' => 'promotion_vacation_leave_with_pay', 'label' => 'Vacation Leave with Pay', 'rules' => 'trim|required'],
            ['field' => 'promotion_others', 'label' => 'Others', 'rules' => 'trim|required'],
            ['field' => 'promotion_total_salary', 'label' => 'Total Salary', 'rules' => 'trim|required'],
            ['field' => 'promotion_point_of_hire', 'label' => 'Point of Hire', 'rules' => 'trim|required'],
            ['field' => 'promotion_collective_agreement', 'label' => 'Collective Agreement', 'rules' => 'trim|required']
        ],
        'mlc_contract_form' => [
            ['field' => 'c_mlc_contract', 'label' => 'Type of Contract', 'rules' => 'trim|required'],
            // ['field' => 'mlc_farer_passport', 'label' => "Passport No.", 'rules' => 'trim|required'],
            // ['field' => 'mlc_farer_book', 'label' => "Seaman's Book No.", 'rules' => 'trim|required'],
            // ['field' => 'mlc_farer_license', 'label' => 'License Number', 'rules' => 'trim|required'],
            ['field' => 'mlc_farer_sex', 'label' => 'Sex', 'rules' => 'trim|required'],
            ['field' => 'mlc_sign_place', 'label' => 'Place', 'rules' => 'trim|required'],
            ['field' => 'mlc_sign_date', 'label' => 'Date', 'rules' => 'trim|required'],
            ['field' => 'mlc_bw', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'mlc_ot', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'mlc_pl', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'mlc_sa', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'mlc_rb', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'mlc_mts', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'mlc_fksu', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'mlc_mt', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'mlc_employment_period_from', 'label' => 'Period of Employment From', 'rules' => 'trim|required'],
            ['field' => 'mlc_employment_period_to', 'label' => 'Period of Employment To', 'rules' => 'trim|required'],
            ['field' => 'mlc_shipowner_vessel', 'label' => 'Shipowner of Vessel', 'rules' => 'trim|required'],
            ['field' => 'mlc_vp_alphera', 'label' => 'Name of VP', 'rules' => 'trim|required'],
        ],
        'edit_mlc_contract_form' => [
            ['field' => 'edit_mlc_sign_place', 'label' => 'Place', 'rules' => 'trim|required'],
            ['field' => 'edit_mlc_sign_date', 'label' => 'Date', 'rules' => 'trim|required'],
            ['field' => 'edit_mlc_bw', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'edit_mlc_ot', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'edit_mlc_pl', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'edit_mlc_sa', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'edit_mlc_rb', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'edit_mlc_mts', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'edit_mlc_fksu', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'edit_mlc_mt', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'edit_mlc_employment_period_from', 'label' => 'Period of Employment From', 'rules' => 'trim|required'],
            ['field' => 'edit_mlc_employment_period_to', 'label' => 'Period of Employment To', 'rules' => 'trim|required'],
        ],
        'promotion_mlc_contract_form' => [
            ['field' => 'promotion_mlc_sign_place', 'label' => 'Place', 'rules' => 'trim|required'],
            ['field' => 'promotion_mlc_sign_date', 'label' => 'Date', 'rules' => 'trim|required'],
            ['field' => 'promotion_mlc_bw', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'promotion_mlc_ot', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'promotion_mlc_pl', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'promotion_mlc_sa', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'promotion_mlc_rb', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'promotion_mlc_mts', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'promotion_mlc_fksu', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'promotion_mlc_mt', 'label' => 'Monthly Wage', 'rules' => 'trim|required'],
            ['field' => 'promotion_mlc_employment_period_from', 'label' => 'Period of Employment From', 'rules' => 'trim|required'],
            ['field' => 'promotion_mlc_employment_period_to', 'label' => 'Period of Employment To', 'rules' => 'trim|required'],
        ],
        'edit_position_promotion' => [
            ['field' => 'epp_position', 'label' => 'Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'epp_tentative_vessel', 'label' => 'Vessel', 'rules' => 'trim|required|callback_validate_select'],
        ],
        'edit_position_vessel' => [
            ['field' => 'epvm_position', 'label' => 'Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'epvm_tentative_vessel', 'label' => 'Vessel', 'rules' => 'trim|required|callback_validate_select'],
        ],
        'crew_withdrawal_application' => [
            ['field' => 'w_rank', 'label' => 'Position', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'w_department', 'label' => 'Department', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'w_vessel', 'label' => 'Vessel', 'rules' => 'trim|required|callback_validate_select'],
            ['field' => 'w_remarks', 'label' => 'Remarks', 'rules' => 'trim|required'],
        ],
        'assign_as_on_signer' => [
            ['field' => 'a_offsigner', 'label' => 'Off Signer', 'rules' => 'trim|required'],
            ['field' => 'a_embarked_date', 'label' => 'Date of Embarkation', 'rules' => 'trim|required'],
            ['field' => 'a_disembarked_date', 'label' => 'Date of Disembarkation', 'rules' => 'trim|required|callback_validate_disembark_date'],
        ],
    ];
}
